PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0005
  milestones: [15, 30, 50]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 20
  use_cl: False
  cl_step_size: 2500

  model_args:
    gpu_num : 0
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    # input_embedding_dim: 24
    # tod_embedding_dim: 24
    # dow_embedding_dim: 24
    # spatial_embedding_dim: 0
    # adaptive_embedding_dim: 80
    input_embedding_dim: 32
    tod_embedding_dim: 32
    dow_embedding_dim: 32
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 132
    feed_forward_dim: 152
    num_layers: 3
    dropout: 0.4
    use_tinyatt: True

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.001
  milestones: [15, 35, 50]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 20
  use_cl: False
  cl_step_size: 2500

  model_args:
    gpu_num : 0
    num_nodes: 883
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 152
    num_layers: 4
    dropout: 0.4
    use_tinyatt: False
    

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    gpu_num : 0
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 152
    num_layers: 3
    dropout: 0.1
    use_tinyatt: True
    